# Generated by Django 5.0.14 on 2025-04-21 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='residents',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='administrator_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBookingWebsite.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBookingWebsite.student')),
            ],
        ),
        migrations.CreateModel(
            name='FurnishingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('furnishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBookingWebsite.furnishing')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBookingWebsite.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBookingWebsite.student')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBookingWebsite.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBookingWebsite.student')),
            ],
        ),
    ]
