# Generated by Django 5.0.14 on 2025-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0002_remove_administrator_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='maintenance_worker',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='room',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='issue_type',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Heating/Cooling', 'Heating/Cooling'), ('Furniture', 'Furniture'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
