# Generated by Django 5.0.14 on 2025-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0003_rename_created_at_maintenancerequest_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='floors',
            field=models.IntegerField(default=-1),
        ),
    ]
