# Generated by Django 5.0.14 on 2025-04-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0003_preferences_student_preferences'),
        ('RoomBookingWebsite', '0004_building_floors'),
    ]

    operations = [
    ]
