# Generated by Django 5.0.14 on 2025-04-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0005_merge_20250424_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bathroom_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Semi-Private', 'Semi-Private'), ('Community', 'Community')], default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='building',
            name='gender',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('other', 'other')], default='-', max_length=50),
        ),
    ]
