# Generated by Django 5.0.14 on 2025-04-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0007_alter_building_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building_name',
            field=models.CharField(default='error', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(default='error', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='RoomBookingWebsite.building'),
        ),
    ]
