# Generated by Django 4.2.6 on 2025-04-26 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0007_alter_building_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roommates',
        ),
        migrations.AddField(
            model_name='student',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentRoommates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('roommates', models.ManyToManyField(blank=True, to='RoomBookingWebsite.studentroommates')),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_set_1', to='RoomBookingWebsite.student')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_set_2', to='RoomBookingWebsite.student')),
            ],
        ),
    ]
