# Generated by Django 5.0.14 on 2025-04-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0008_remove_student_roommates_student_matched_and_more'),
        ('RoomBookingWebsite', '0008_room_building_name_alter_building_name_and_more'),
    ]

    operations = [
    ]
