# Generated by Django 5.0.14 on 2025-04-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0010_alter_room_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=50),
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBookingWebsite.maintenancerequest')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RoomBookingWebsite.maintenanceworker')),
            ],
        ),
    ]
