# Generated by Django 5.0.14 on 2025-04-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingWebsite', '0011_maintenancerequest_status_maintenanceticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnishingrequest',
            name='issue_description',
        ),
        migrations.AddField(
            model_name='furnishingrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
